In [12]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.metrics import mean_squared_error
import sklearn.model_selection

In [6]:
data=pd.read_csv("D:\\CVID DATA.csv")
data.head()

Fever   Age   BodyPain  DifficultyinBreath  RunnyNose  Travel   Cough  \
0     101   65          1                   0          0        1      1   
1      98   59          0                   1          0        1      1   
2     103   46          0                   1          1        0      0   
3     104   83          0                   0          0        0      1   
4      98   98          0                   0          1        0      0   

   Probability  
0            1  
1            0  
2            0  
3            0  
4            0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fever               1999 non-null   int64
 1   Age                 1999 non-null   int64
 2    BodyPain           1999 non-null   int64
 3   DifficultyinBreath  1999 non-null   int64
 4   RunnyNose           1999 non-null   int64
 5   Travel              1999 non-null   int64
 6   Cough               1999 non-null   int64
 7   Probability         1999 non-null   int64
dtypes: int64(8)
memory usage: 125.1 KB


In [9]:
X=data.drop('Probability',axis=1)
print(X.head())
print('data in y')
Y=data["Probability"]
Y.head()

   Fever   Age   BodyPain  DifficultyinBreath  RunnyNose  Travel   Cough
0     101   65          1                   0          0        1      1
1      98   59          0                   1          0        1      1
2     103   46          0                   1          1        0      0
3     104   83          0                   0          0        0      1
4      98   98          0                   0          1        0      0
data in y


0    1
1    0
2    0
3    0
4    0
Name: Probability, dtype: int64

In [13]:
X_train, X_test, Y_train, Y_test = sklearn.model_selection.train_test_split(X, Y, test_size = 0.33, random_state = 5)

In [14]:
print(X_train.to_numpy())

Y_train.to_numpy()

X_test.to_numpy()

Y_test.to_numpy()

[[101  16   1 ...   0   0   1]
 [ 98  25   1 ...   0   0   0]
 [104  53   0 ...   1   1   0]
 ...
 [103  63   0 ...   0   1   1]
 [104  38   1 ...   1   1   1]
 [ 98 100   0 ...   1   1   1]]


array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [15]:
from sklearn.linear_model import LogisticRegression

clf =LogisticRegression()



Y_train_pred=clf.fit(X_train,Y_train)

In [16]:
infection=clf.predict([[98,20,0,1,0,0,0]])



infection_probability= clf.predict_proba([[98,20,0,0,0,0,1]])

print(infection)

print(infection_probability)

[0]
[[0.47974979 0.52025021]]
